services:
  - type: web
    name: gazhunters-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/test
    autoDeploy: true
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: NOTIFICATION_EMAIL
        sync: false
      - key: PORT
        value: 10000


